# --------------------------------------------------------------
# DeleteArea - DELETE
# --------------------------------------------------------------
$name: deleteArea
$description: "Supprime une zone par son identifiant"
$skip: false
$async: true

$params:
  - $name: areaId
    $type: string
    $optional: false

$returnDescription: "Confirmation de suppression"
$returnType:
  $type: object
  $nullable: true

$rewriteInController: true
$rewriteInDataSourceImpl: true
$rewriteInDataSource: true
$rewriteInRepository: true
$implementationInDataSource:
  $type: api
  $client: fetch
  $endpoint: CONFIG.DELETE_AREA
  $mapping:
    $path:
      area_id: areaId
  $responseMapping:
    $returnValue: ""
