# --------------------------------------------------------------
# ReorderArea - PATCH
# --------------------------------------------------------------
$name: reorderArea
$description: "Réordonne une zone"
$skip: false
$async: true

$params:
  - $name: areaId
    $type: string
    $optional: false
  - $name: new_order
    $type: number
    $optional: false

$returnDescription: "Résultat du réordonnancement"
$returnType:
  $type: object
  $nullable: true

$rewriteInController: true
$rewriteInDataSourceImpl: true
$rewriteInDataSource: true
$rewriteInRepository: true
$implementationInDataSource:
  $type: api
  $client: fetch
  $endpoint: CONFIG.REORDER_AREA
  $mapping:
    $path:
      area_id: areaId
    $body:
      new_order: new_order
  $responseMapping:
    $returnValue: ""
