# --------------------------------------------------------------
# DeleteItem - DELETE
# --------------------------------------------------------------
$name: deleteItem
$description: "Supprime un item par son identifiant"
$skip: false
$async: true

$params:
  - $name: itemId
    $type: string
    $optional: false

$returnDescription: "Confirmation de suppression"
$returnType:
  $type: object
  $nullable: true

$rewriteInController: true
$rewriteInDataSourceImpl: true
$rewriteInDataSource: true
$rewriteInRepository: true
$implementationInDataSource:
  $type: api
  $client: fetch
  $endpoint: CONFIG.DELETE_ITEM
  $mapping:
    $path:
      item_id: itemId
  $responseMapping:
    $returnValue: ""
