# --------------------------------------------------------------
# RemoveItemCategories - POST
# --------------------------------------------------------------
$name: removeItemCategories
$description: "Retire des catégories d'un item"
$skip: false
$async: true

$params:
  - $name: itemId
    $type: string
    $optional: false
  - $name: category_ids
    $type: string
    $list: true
    $optional: false

$returnDescription: "Résultat du retrait de catégories"
$returnType:
  $type: object
  $nullable: true

$rewriteInController: true
$rewriteInDataSourceImpl: true
$rewriteInDataSource: true
$rewriteInRepository: true
$implementationInDataSource:
  $type: api
  $client: fetch
  $endpoint: CONFIG.REMOVE_ITEM_CATEGORIES
  $mapping:
    $path:
      item_id: itemId
    $body:
      category_ids: category_ids
  $responseMapping:
    $returnValue: ""
