import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider"
import { geistSans, geistMono, kablammo, localGeistMono } from "@/app/styles/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: '/manifest',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${kablammo.variable} ${localGeistMono.variable} antialiased overflow-x-hidden`}
      >
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem={false}
            disableTransitionOnChange

          >
        {children}
          </ThemeProvider>
      </body>
    </html> 
  );
}
