# --------------------------------------------------------------
# CreateTable - POST
# --------------------------------------------------------------
$name: createTable
$description: "Crée une nouvelle table"
$skip: false
$async: true

$params:
  - $name: payload
    $type: CreateTablePayload
    $optional: false
    $related: "--module config --feature table_management --kind custom --step feature"

$returnDescription: "La table créée"
$returnType:
  $type: TableBasic
  $nullable: true
  $related:
    - $name: TableBasic
      $module: config
      $kind: custom
      $step: module

$rewriteInController: true
$rewriteInDataSourceImpl: false
$rewriteInDataSource: true
$rewriteInRepository: true
$implementationInDataSource:
  $type: api
  $client: fetch
  $endpoint: CONFIG.CREATE_TABLE
  $mapping:
    $body:
      payload: payload
  $responseMapping:
    $returnValue: ""

$imports:
  - $name: CreateTablePayload
    $from: "--module config --feature table_management --kind custom --step feature"
    $step: feature
  - $name: TableBasic
    $from: "--module config --kind custom --step module"
    $step: module
