# --------------------------------------------------------------
# UpdateKitchen - PUT
# --------------------------------------------------------------
$name: updateKitchen
$description: "Met à jour complètement une cuisine"
$skip: false
$async: true

$params:
  - { $name: kitchenId, $type: string, $optional: false }
  - $name: payload
    $type: CreateKitchenPayload
    $optional: false
    $related: "--module config --feature kitchen_management --kind custom --step feature"

$returnDescription: "La cuisine mise à jour"
$returnType:
  $type: KitchenBasic
  $nullable: true
  $related:
    - $name: KitchenBasic
      $module: config
      $kind: custom
      $step: module

$rewriteInController: true
$rewriteInDataSourceImpl: true
$implementationInDataSource:
  $type: api
  $client: fetch
  $endpoint: CONFIG.UPDATE_KITCHEN
  $mapping:
    $path:
      kitchen_id: kitchenId
    $body:
      payload: payload
  $responseMapping:
    $returnValue: data

$imports:
  - $name: CreateKitchenPayload
    $from: "--module config --feature kitchen_management --kind custom --step feature"
    $step: feature
  - $name: KitchenBasic
    $from: "--module config --kind custom --step module"
    $step: module
