# --------------------------------------------------------------
# ActivateSetMenu - POST
# --------------------------------------------------------------
$name: activateSetMenu
$description: "Active un menu composé par son identifiant"
$skip: false
$async: true

$params:
  - $name: setMenuId
    $type: string
    $optional: false

$returnDescription: "Le menu composé activé"
$returnType:
  $type: SetMenuBasic
  $nullable: true
  $related:
    - $name: SetMenuBasic
      $module: config
      $kind: custom
      $step: module

$rewriteInController: true
$rewriteInDataSourceImpl: true
$rewriteInDataSource: true
$rewriteInRepository: true
$implementationInDataSource:
  $type: api
  $client: fetch
  $endpoint: CONFIG.ACTIVATE_SET_MENU
  $mapping:
    $path:
      set_menu_id: setMenuId
  $responseMapping:
    $returnValue: ""

$imports:
  - $name: SetMenuBasic
    $from: "--module config --kind custom --step module"
    $step: module
