# --------------------------------------------------------------
# AddSetMenuSectionItems - POST
# --------------------------------------------------------------
$name: addSetMenuSectionItems
$description: "Ajoute des items à une section de menu composé"
$skip: false
$async: true

$params:
  - $name: setMenuSectionId
    $type: string
    $optional: false
  - $name: payload
    $type: SetMenuSectionItemsPayload
    $optional: false
    $related: "--module config --feature set_menu_management --kind custom --step feature"

$returnDescription: "Résultat de l'ajout d'items à la section"
$returnType:
  $type: object
  $nullable: true

$rewriteInController: true
$rewriteInDataSourceImpl: true
$rewriteInDataSource: true
$rewriteInRepository: true
$implementationInDataSource:
  $type: api
  $client: fetch
  $endpoint: CONFIG.ADD_SET_MENU_SECTION_ITEMS
  $mapping:
    $path:
      set_menu_section_id: setMenuSectionId
    $body:
      payload: payload
  $responseMapping:
    $returnValue: ""

$imports:
  - $name: SetMenuSectionItemsPayload
    $from: "--module config --feature set_menu_management --kind custom --step feature"
    $step: feature
