# --------------------------------------------------------------
# CreateSetMenuSection - POST
# --------------------------------------------------------------
$name: createSetMenuSection
$description: "Crée une nouvelle section de menu composé"
$skip: false
$async: true

$params:
  - $name: payload
    $type: CreateSetMenuSectionPayload
    $optional: false
    $related: "--module config --feature set_menu_management --kind custom --step feature"

$returnDescription: "La section de menu composé créée"
$returnType:
  $type: SetMenuSectionBasic
  $nullable: true
  $related:
    - $name: SetMenuSectionBasic
      $module: config
      $kind: custom
      $step: module

$rewriteInController: true
$rewriteInDataSourceImpl: true
$rewriteInDataSource: true
$rewriteInRepository: true
$implementationInDataSource:
  $type: api
  $client: fetch
  $endpoint: CONFIG.CREATE_SET_MENU_SECTION
  $mapping:
    $body:
      payload: payload
  $responseMapping:
    $returnValue: ""

$imports:
  - $name: CreateSetMenuSectionPayload
    $from: "--module config --feature set_menu_management --kind custom --step feature"
    $step: feature
  - $name: SetMenuSectionBasic
    $from: "--module config --kind custom --step module"
    $step: module
