# --------------------------------------------------------------
# ReorderSetMenu - PATCH
# --------------------------------------------------------------
$name: reorderSetMenu
$description: "Réordonne un menu composé"
$skip: false
$async: true

$params:
  - $name: setMenuId
    $type: string
    $optional: false
  - $name: new_order
    $type: number
    $optional: false

$returnDescription: "Résultat du réordonnancement"
$returnType:
  $type: object
  $nullable: true

$rewriteInController: true
$rewriteInDataSourceImpl: true
$rewriteInDataSource: true
$rewriteInRepository: true
$implementationInDataSource:
  $type: api
  $client: fetch
  $endpoint: CONFIG.REORDER_SET_MENU
  $mapping:
    $path:
      set_menu_id: setMenuId
    $body:
      new_order: new_order
  $responseMapping:
    $returnValue: ""
