# ------------------------------------------------------------------
# DEACTIVATE_OPTION_GROUP - Désactiver un groupe d'options
# ------------------------------------------------------------------
$path: /config/option-groups/{option_group_id}/deactivate/
$method: POST
$description: "Désactiver un groupe d'options"
$auth: true
$skip: false
$params:
  $path:
    option_group_id: { $type: number, $optional: false }
  $body: {}
$response:
  $default:
    $schema:
      message: { $type: string }
  $byStatus:
    "404":
      $schema:
        detail: { $type: string }
