# ------------------------------------------------------------------
# DELETE_QUANTITY_TYPE - Supprimer un type de quantité
# ------------------------------------------------------------------
$path: /config/quantity-types/{quantity_type_id}/
$method: DELETE
$description: "Supprimer un type de quantité"
$auth: true
$skip: false
$params:
  $path:
    quantity_type_id: { $type: number, $optional: false }
$response:
  $default:
    $description: "204 No Content"
    $schema:
      message: { $type: string }
  $byStatus:
    "404":
      $schema:
        detail: { $type: string }
