# --------------------------------------------------------------
# DeleteDynamicConfig - DELETE
# --------------------------------------------------------------
$name: deleteDynamicConfig
$description: "Supprime une configuration dynamique par son identifiant"
$skip: false
$async: true

$params:
  - $name: configId
    $type: string
    $optional: false

$returnDescription: "Confirmation de suppression"
$returnType:
  $type: object
  $nullable: true

$rewriteInController: true
$rewriteInDataSourceImpl: true
$rewriteInDataSource: true
$rewriteInRepository: true
$implementationInDataSource:
  $type: api
  $client: fetch
  $endpoint: CONFIG.DELETE_DYNAMIC_CONFIG
  $mapping:
    $path:
      config_id: configId
  $responseMapping:
    $returnValue: ""
