# --------------------------------------------------------------
# DeactivateOption - POST
# --------------------------------------------------------------
$name: deactivateOption
$description: "Désactive une option par son identifiant"
$skip: false
$async: true

$params:
  - $name: optionId
    $type: string
    $optional: false

$returnDescription: "L'option désactivée"
$returnType:
  $type: OptionBasic
  $nullable: true
  $related:
    - $name: OptionBasic
      $module: config
      $kind: custom
      $step: module

$rewriteInController: true
$rewriteInDataSourceImpl: true
$rewriteInDataSource: true
$rewriteInRepository: true
$implementationInDataSource:
  $type: api
  $client: fetch
  $endpoint: CONFIG.DEACTIVATE_OPTION
  $mapping:
    $path:
      option_id: optionId
  $responseMapping:
    $returnValue: ""

$imports:
  - $name: OptionBasic
    $from: "--module config --kind custom --step module"
    $step: module
