# --------------------------------------------------------------
# CreateOptionGroup - POST
# --------------------------------------------------------------
$name: createOptionGroup
$description: "Crée un nouveau groupe d'options"
$skip: false
$async: true

$params:
  - $name: payload
    $type: CreateOptionGroupPayload
    $optional: false
    $related: "--module config --feature option_group_management --kind custom --step feature"

$returnDescription: "Le groupe d'options créé"
$returnType:
  $type: OptionGroupBasic
  $nullable: true
  $related:
    - $name: OptionGroupBasic
      $module: config
      $kind: custom
      $step: module

$rewriteInController: true
$rewriteInDataSourceImpl: true
$rewriteInDataSource: true
$rewriteInRepository: true
$implementationInDataSource:
  $type: api
  $client: fetch
  $endpoint: CONFIG.CREATE_OPTION_GROUP
  $mapping:
    $body:
      payload: payload
  $responseMapping:
    $returnValue: ""

$imports:
  - $name: CreateOptionGroupPayload
    $from: "--module config --feature option_group_management --kind custom --step feature"
    $step: feature
  - $name: OptionGroupBasic
    $from: "--module config --kind custom --step module"
    $step: module
