# --------------------------------------------------------------
# DeleteOptionGroup - DELETE
# --------------------------------------------------------------
$name: deleteOptionGroup
$description: "Supprime un groupe d'options par son identifiant"
$skip: false
$async: true

$params:
  - $name: optionGroupId
    $type: string
    $optional: false

$returnDescription: "Confirmation de suppression"
$returnType:
  $type: object
  $nullable: true

$rewriteInController: true
$rewriteInDataSourceImpl: true
$rewriteInDataSource: true
$rewriteInRepository: true
$implementationInDataSource:
  $type: api
  $client: fetch
  $endpoint: CONFIG.DELETE_OPTION_GROUP
  $mapping:
    $path:
      option_group_id: optionGroupId
  $responseMapping:
    $returnValue: ""
