# --------------------------------------------------------------
# GetOptionGroupsList - GET
# --------------------------------------------------------------
$name: getOptionGroupsList
$description: "Liste tous les groupes d'options avec pagination et filtres"
$skip: false
$async: true

$params:
  - $name: is_active
    $type: boolean
    $optional: true
  - $name: search
    $type: string
    $optional: true
  - $name: ordering
    $type: string
    $optional: true

$returnDescription: "Liste paginée des groupes d'options"
$returnType:
  $type: PaginatedOptionGroups
  $nullable: true
  $related:
    - $name: PaginatedOptionGroups
      $module: config
      $kind: custom
      $step: module

$rewriteInController: true
$rewriteInDataSourceImpl: true
$rewriteInDataSource: true
$rewriteInRepository: true
$implementationInDataSource:
  $type: api
  $client: fetch
  $endpoint: CONFIG.GET_OPTION_GROUPS_LIST
  $mapping:
    $query:
      is_active: is_active
      search: search
      ordering: ordering
  $responseMapping:
    $returnValue: ""

$imports:
  - $name: PaginatedOptionGroups
    $from: "--module config --kind custom --step module"
    $step: module
